languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXX-Y"
defaultContentLanguage = "nl"

[params]
    description = "Portfolio of Thomas, Senior Data Scientist | Machine Learning Engineer"
    favicon = "tca1.png"
    logo = "tca1.png"
    logo_nav = "tca2.png"
    email = "info@tca-datasolutions.nl"
    linkedin = "https://www.linkedin.com/in/thomas-castelijns"
    github = "TCACastelijns"
    main_color="#000080"

[params.nav]
    quote='"The value of the data lies in the using of it." '
    enable = true

[params.hero]
    enable = true
    avatar = "profile.jpg"
    title = "Thomas Castelijns"
    subtitle = "Freelance Data Scientist & Machine Learning Engineer"
    hero_right = ["# About",
        "## Technology, Consultancy & Analytics",
        "I have 3+ years experience in leading a Data Science Development and Operations team. From this I know how hard it can be to translate your business data into valueble insights. It is my strength to help companies and organisations in becoming more data driven and captialize on their data. The value is not the data itself, but the value lies in the using of it.",
        "I am proficient in data preprocessing, visualization, predictive modeling and getting these into your ICT infrastructure.",
        "Do you want to reach the next level in your data maturity? Please reach out to me by [e-mail](mailto:thomascastelijns@live.nl) or [LinkedIn](https://www.linkedin.com/in/thomas-castelijns)."]

[params.process]
    enable = true
    title = "Way of Working "
    subtitle = "Services"

[params.case_studies]
    enable = true
    title = "Project portfolio"
    subtitle = "Selected Works"

[params.contact]
    enable = true
    title = "Contact "
    subtitle = "Contact details"

[params.footer]
    enable = true



[languages]
    [languages.en]
        title = "TCA data solutions - The value of the data lies in the using of it"
        baseURL = "https://tca-datasolutions.com/"
        languageName='English'
        weight = 2
    [languages.nl]
        title = "TCA data solutions - De waarde van data zit hem in het gebruik ervan"
        baseURL = "https://tca-datasolutions.nl/"
        languageName='Nederlands'
        weight = 1
        [languages.nl.params.case_studies]
            enable=true
            title = "HAA"
            subtitle = "Mijn werk"